/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * This file exports the `CvSection` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from '@prisma/client/runtime/client'
import type * as $Enums from '../enums.js'
import type * as Prisma from '../internal/prismaNamespace.js'

/**
 * Model CvSection
 *
 */
export type CvSectionModel = runtime.Types.Result.DefaultSelection<Prisma.$CvSectionPayload>

export type AggregateCvSection = {
  _count: CvSectionCountAggregateOutputType | null
  _avg: CvSectionAvgAggregateOutputType | null
  _sum: CvSectionSumAggregateOutputType | null
  _min: CvSectionMinAggregateOutputType | null
  _max: CvSectionMaxAggregateOutputType | null
}

export type CvSectionAvgAggregateOutputType = {
  order: number | null
}

export type CvSectionSumAggregateOutputType = {
  order: number | null
}

export type CvSectionMinAggregateOutputType = {
  id: string | null
  cvId: string | null
  type: $Enums.CvSectionType | null
  order: number | null
}

export type CvSectionMaxAggregateOutputType = {
  id: string | null
  cvId: string | null
  type: $Enums.CvSectionType | null
  order: number | null
}

export type CvSectionCountAggregateOutputType = {
  id: number
  cvId: number
  type: number
  order: number
  _all: number
}

export type CvSectionAvgAggregateInputType = {
  order?: true
}

export type CvSectionSumAggregateInputType = {
  order?: true
}

export type CvSectionMinAggregateInputType = {
  id?: true
  cvId?: true
  type?: true
  order?: true
}

export type CvSectionMaxAggregateInputType = {
  id?: true
  cvId?: true
  type?: true
  order?: true
}

export type CvSectionCountAggregateInputType = {
  id?: true
  cvId?: true
  type?: true
  order?: true
  _all?: true
}

export type CvSectionAggregateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which CvSection to aggregate.
   */
  where?: Prisma.CvSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CvSections to fetch.
   */
  orderBy?: Prisma.CvSectionOrderByWithRelationInput | Prisma.CvSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the start position
   */
  cursor?: Prisma.CvSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CvSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CvSections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Count returned CvSections
   **/
  _count?: true | CvSectionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to average
   **/
  _avg?: CvSectionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to sum
   **/
  _sum?: CvSectionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the minimum value
   **/
  _min?: CvSectionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   *
   * Select which fields to find the maximum value
   **/
  _max?: CvSectionMaxAggregateInputType
}

export type GetCvSectionAggregateType<T extends CvSectionAggregateArgs> = {
  [P in keyof T & keyof AggregateCvSection]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateCvSection[P]>
    : Prisma.GetScalarType<T[P], AggregateCvSection[P]>
}

export type CvSectionGroupByArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.CvSectionWhereInput
  orderBy?: Prisma.CvSectionOrderByWithAggregationInput | Prisma.CvSectionOrderByWithAggregationInput[]
  by: Prisma.CvSectionScalarFieldEnum[] | Prisma.CvSectionScalarFieldEnum
  having?: Prisma.CvSectionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: CvSectionCountAggregateInputType | true
  _avg?: CvSectionAvgAggregateInputType
  _sum?: CvSectionSumAggregateInputType
  _min?: CvSectionMinAggregateInputType
  _max?: CvSectionMaxAggregateInputType
}

export type CvSectionGroupByOutputType = {
  id: string
  cvId: string
  type: $Enums.CvSectionType
  order: number
  _count: CvSectionCountAggregateOutputType | null
  _avg: CvSectionAvgAggregateOutputType | null
  _sum: CvSectionSumAggregateOutputType | null
  _min: CvSectionMinAggregateOutputType | null
  _max: CvSectionMaxAggregateOutputType | null
}

type GetCvSectionGroupByPayload<T extends CvSectionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<CvSectionGroupByOutputType, T['by']> & {
      [P in keyof T & keyof CvSectionGroupByOutputType]: P extends '_count'
        ? T[P] extends boolean
          ? number
          : Prisma.GetScalarType<T[P], CvSectionGroupByOutputType[P]>
        : Prisma.GetScalarType<T[P], CvSectionGroupByOutputType[P]>
    }
  >
>

export type CvSectionWhereInput = {
  AND?: Prisma.CvSectionWhereInput | Prisma.CvSectionWhereInput[]
  OR?: Prisma.CvSectionWhereInput[]
  NOT?: Prisma.CvSectionWhereInput | Prisma.CvSectionWhereInput[]
  id?: Prisma.StringFilter<'CvSection'> | string
  cvId?: Prisma.StringFilter<'CvSection'> | string
  type?: Prisma.EnumCvSectionTypeFilter<'CvSection'> | $Enums.CvSectionType
  order?: Prisma.IntFilter<'CvSection'> | number
  cv?: Prisma.XOR<Prisma.CvScalarRelationFilter, Prisma.CvWhereInput>
  chunks?: Prisma.CvChunkListRelationFilter
}

export type CvSectionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  cvId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  order?: Prisma.SortOrder
  cv?: Prisma.CvOrderByWithRelationInput
  chunks?: Prisma.CvChunkOrderByRelationAggregateInput
}

export type CvSectionWhereUniqueInput = Prisma.AtLeast<
  {
    id?: string
    AND?: Prisma.CvSectionWhereInput | Prisma.CvSectionWhereInput[]
    OR?: Prisma.CvSectionWhereInput[]
    NOT?: Prisma.CvSectionWhereInput | Prisma.CvSectionWhereInput[]
    cvId?: Prisma.StringFilter<'CvSection'> | string
    type?: Prisma.EnumCvSectionTypeFilter<'CvSection'> | $Enums.CvSectionType
    order?: Prisma.IntFilter<'CvSection'> | number
    cv?: Prisma.XOR<Prisma.CvScalarRelationFilter, Prisma.CvWhereInput>
    chunks?: Prisma.CvChunkListRelationFilter
  },
  'id'
>

export type CvSectionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  cvId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  order?: Prisma.SortOrder
  _count?: Prisma.CvSectionCountOrderByAggregateInput
  _avg?: Prisma.CvSectionAvgOrderByAggregateInput
  _max?: Prisma.CvSectionMaxOrderByAggregateInput
  _min?: Prisma.CvSectionMinOrderByAggregateInput
  _sum?: Prisma.CvSectionSumOrderByAggregateInput
}

export type CvSectionScalarWhereWithAggregatesInput = {
  AND?: Prisma.CvSectionScalarWhereWithAggregatesInput | Prisma.CvSectionScalarWhereWithAggregatesInput[]
  OR?: Prisma.CvSectionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.CvSectionScalarWhereWithAggregatesInput | Prisma.CvSectionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<'CvSection'> | string
  cvId?: Prisma.StringWithAggregatesFilter<'CvSection'> | string
  type?: Prisma.EnumCvSectionTypeWithAggregatesFilter<'CvSection'> | $Enums.CvSectionType
  order?: Prisma.IntWithAggregatesFilter<'CvSection'> | number
}

export type CvSectionCreateInput = {
  id?: string
  type: $Enums.CvSectionType
  order: number
  cv: Prisma.CvCreateNestedOneWithoutSectionsInput
  chunks?: Prisma.CvChunkCreateNestedManyWithoutSectionInput
}

export type CvSectionUncheckedCreateInput = {
  id?: string
  cvId: string
  type: $Enums.CvSectionType
  order: number
  chunks?: Prisma.CvChunkUncheckedCreateNestedManyWithoutSectionInput
}

export type CvSectionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCvSectionTypeFieldUpdateOperationsInput | $Enums.CvSectionType
  order?: Prisma.IntFieldUpdateOperationsInput | number
  cv?: Prisma.CvUpdateOneRequiredWithoutSectionsNestedInput
  chunks?: Prisma.CvChunkUpdateManyWithoutSectionNestedInput
}

export type CvSectionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cvId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCvSectionTypeFieldUpdateOperationsInput | $Enums.CvSectionType
  order?: Prisma.IntFieldUpdateOperationsInput | number
  chunks?: Prisma.CvChunkUncheckedUpdateManyWithoutSectionNestedInput
}

export type CvSectionCreateManyInput = {
  id?: string
  cvId: string
  type: $Enums.CvSectionType
  order: number
}

export type CvSectionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCvSectionTypeFieldUpdateOperationsInput | $Enums.CvSectionType
  order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CvSectionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cvId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCvSectionTypeFieldUpdateOperationsInput | $Enums.CvSectionType
  order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CvSectionListRelationFilter = {
  every?: Prisma.CvSectionWhereInput
  some?: Prisma.CvSectionWhereInput
  none?: Prisma.CvSectionWhereInput
}

export type CvSectionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type CvSectionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cvId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type CvSectionAvgOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type CvSectionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cvId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type CvSectionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  cvId?: Prisma.SortOrder
  type?: Prisma.SortOrder
  order?: Prisma.SortOrder
}

export type CvSectionSumOrderByAggregateInput = {
  order?: Prisma.SortOrder
}

export type CvSectionScalarRelationFilter = {
  is?: Prisma.CvSectionWhereInput
  isNot?: Prisma.CvSectionWhereInput
}

export type CvSectionCreateNestedManyWithoutCvInput = {
  create?:
    | Prisma.XOR<Prisma.CvSectionCreateWithoutCvInput, Prisma.CvSectionUncheckedCreateWithoutCvInput>
    | Prisma.CvSectionCreateWithoutCvInput[]
    | Prisma.CvSectionUncheckedCreateWithoutCvInput[]
  connectOrCreate?: Prisma.CvSectionCreateOrConnectWithoutCvInput | Prisma.CvSectionCreateOrConnectWithoutCvInput[]
  createMany?: Prisma.CvSectionCreateManyCvInputEnvelope
  connect?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
}

export type CvSectionUncheckedCreateNestedManyWithoutCvInput = {
  create?:
    | Prisma.XOR<Prisma.CvSectionCreateWithoutCvInput, Prisma.CvSectionUncheckedCreateWithoutCvInput>
    | Prisma.CvSectionCreateWithoutCvInput[]
    | Prisma.CvSectionUncheckedCreateWithoutCvInput[]
  connectOrCreate?: Prisma.CvSectionCreateOrConnectWithoutCvInput | Prisma.CvSectionCreateOrConnectWithoutCvInput[]
  createMany?: Prisma.CvSectionCreateManyCvInputEnvelope
  connect?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
}

export type CvSectionUpdateManyWithoutCvNestedInput = {
  create?:
    | Prisma.XOR<Prisma.CvSectionCreateWithoutCvInput, Prisma.CvSectionUncheckedCreateWithoutCvInput>
    | Prisma.CvSectionCreateWithoutCvInput[]
    | Prisma.CvSectionUncheckedCreateWithoutCvInput[]
  connectOrCreate?: Prisma.CvSectionCreateOrConnectWithoutCvInput | Prisma.CvSectionCreateOrConnectWithoutCvInput[]
  upsert?: Prisma.CvSectionUpsertWithWhereUniqueWithoutCvInput | Prisma.CvSectionUpsertWithWhereUniqueWithoutCvInput[]
  createMany?: Prisma.CvSectionCreateManyCvInputEnvelope
  set?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
  disconnect?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
  delete?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
  connect?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
  update?: Prisma.CvSectionUpdateWithWhereUniqueWithoutCvInput | Prisma.CvSectionUpdateWithWhereUniqueWithoutCvInput[]
  updateMany?: Prisma.CvSectionUpdateManyWithWhereWithoutCvInput | Prisma.CvSectionUpdateManyWithWhereWithoutCvInput[]
  deleteMany?: Prisma.CvSectionScalarWhereInput | Prisma.CvSectionScalarWhereInput[]
}

export type CvSectionUncheckedUpdateManyWithoutCvNestedInput = {
  create?:
    | Prisma.XOR<Prisma.CvSectionCreateWithoutCvInput, Prisma.CvSectionUncheckedCreateWithoutCvInput>
    | Prisma.CvSectionCreateWithoutCvInput[]
    | Prisma.CvSectionUncheckedCreateWithoutCvInput[]
  connectOrCreate?: Prisma.CvSectionCreateOrConnectWithoutCvInput | Prisma.CvSectionCreateOrConnectWithoutCvInput[]
  upsert?: Prisma.CvSectionUpsertWithWhereUniqueWithoutCvInput | Prisma.CvSectionUpsertWithWhereUniqueWithoutCvInput[]
  createMany?: Prisma.CvSectionCreateManyCvInputEnvelope
  set?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
  disconnect?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
  delete?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
  connect?: Prisma.CvSectionWhereUniqueInput | Prisma.CvSectionWhereUniqueInput[]
  update?: Prisma.CvSectionUpdateWithWhereUniqueWithoutCvInput | Prisma.CvSectionUpdateWithWhereUniqueWithoutCvInput[]
  updateMany?: Prisma.CvSectionUpdateManyWithWhereWithoutCvInput | Prisma.CvSectionUpdateManyWithWhereWithoutCvInput[]
  deleteMany?: Prisma.CvSectionScalarWhereInput | Prisma.CvSectionScalarWhereInput[]
}

export type EnumCvSectionTypeFieldUpdateOperationsInput = {
  set?: $Enums.CvSectionType
}

export type IntFieldUpdateOperationsInput = {
  set?: number
  increment?: number
  decrement?: number
  multiply?: number
  divide?: number
}

export type CvSectionUpdateOneRequiredWithoutChunksNestedInput = {
  create?: Prisma.XOR<Prisma.CvSectionCreateWithoutChunksInput, Prisma.CvSectionUncheckedCreateWithoutChunksInput>
  connectOrCreate?: Prisma.CvSectionCreateOrConnectWithoutChunksInput
  upsert?: Prisma.CvSectionUpsertWithoutChunksInput
  connect?: Prisma.CvSectionWhereUniqueInput
  update?: Prisma.XOR<
    Prisma.XOR<Prisma.CvSectionUpdateToOneWithWhereWithoutChunksInput, Prisma.CvSectionUpdateWithoutChunksInput>,
    Prisma.CvSectionUncheckedUpdateWithoutChunksInput
  >
}

export type CvSectionCreateWithoutCvInput = {
  id?: string
  type: $Enums.CvSectionType
  order: number
  chunks?: Prisma.CvChunkCreateNestedManyWithoutSectionInput
}

export type CvSectionUncheckedCreateWithoutCvInput = {
  id?: string
  type: $Enums.CvSectionType
  order: number
  chunks?: Prisma.CvChunkUncheckedCreateNestedManyWithoutSectionInput
}

export type CvSectionCreateOrConnectWithoutCvInput = {
  where: Prisma.CvSectionWhereUniqueInput
  create: Prisma.XOR<Prisma.CvSectionCreateWithoutCvInput, Prisma.CvSectionUncheckedCreateWithoutCvInput>
}

export type CvSectionCreateManyCvInputEnvelope = {
  data: Prisma.CvSectionCreateManyCvInput | Prisma.CvSectionCreateManyCvInput[]
  skipDuplicates?: boolean
}

export type CvSectionUpsertWithWhereUniqueWithoutCvInput = {
  where: Prisma.CvSectionWhereUniqueInput
  update: Prisma.XOR<Prisma.CvSectionUpdateWithoutCvInput, Prisma.CvSectionUncheckedUpdateWithoutCvInput>
  create: Prisma.XOR<Prisma.CvSectionCreateWithoutCvInput, Prisma.CvSectionUncheckedCreateWithoutCvInput>
}

export type CvSectionUpdateWithWhereUniqueWithoutCvInput = {
  where: Prisma.CvSectionWhereUniqueInput
  data: Prisma.XOR<Prisma.CvSectionUpdateWithoutCvInput, Prisma.CvSectionUncheckedUpdateWithoutCvInput>
}

export type CvSectionUpdateManyWithWhereWithoutCvInput = {
  where: Prisma.CvSectionScalarWhereInput
  data: Prisma.XOR<Prisma.CvSectionUpdateManyMutationInput, Prisma.CvSectionUncheckedUpdateManyWithoutCvInput>
}

export type CvSectionScalarWhereInput = {
  AND?: Prisma.CvSectionScalarWhereInput | Prisma.CvSectionScalarWhereInput[]
  OR?: Prisma.CvSectionScalarWhereInput[]
  NOT?: Prisma.CvSectionScalarWhereInput | Prisma.CvSectionScalarWhereInput[]
  id?: Prisma.StringFilter<'CvSection'> | string
  cvId?: Prisma.StringFilter<'CvSection'> | string
  type?: Prisma.EnumCvSectionTypeFilter<'CvSection'> | $Enums.CvSectionType
  order?: Prisma.IntFilter<'CvSection'> | number
}

export type CvSectionCreateWithoutChunksInput = {
  id?: string
  type: $Enums.CvSectionType
  order: number
  cv: Prisma.CvCreateNestedOneWithoutSectionsInput
}

export type CvSectionUncheckedCreateWithoutChunksInput = {
  id?: string
  cvId: string
  type: $Enums.CvSectionType
  order: number
}

export type CvSectionCreateOrConnectWithoutChunksInput = {
  where: Prisma.CvSectionWhereUniqueInput
  create: Prisma.XOR<Prisma.CvSectionCreateWithoutChunksInput, Prisma.CvSectionUncheckedCreateWithoutChunksInput>
}

export type CvSectionUpsertWithoutChunksInput = {
  update: Prisma.XOR<Prisma.CvSectionUpdateWithoutChunksInput, Prisma.CvSectionUncheckedUpdateWithoutChunksInput>
  create: Prisma.XOR<Prisma.CvSectionCreateWithoutChunksInput, Prisma.CvSectionUncheckedCreateWithoutChunksInput>
  where?: Prisma.CvSectionWhereInput
}

export type CvSectionUpdateToOneWithWhereWithoutChunksInput = {
  where?: Prisma.CvSectionWhereInput
  data: Prisma.XOR<Prisma.CvSectionUpdateWithoutChunksInput, Prisma.CvSectionUncheckedUpdateWithoutChunksInput>
}

export type CvSectionUpdateWithoutChunksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCvSectionTypeFieldUpdateOperationsInput | $Enums.CvSectionType
  order?: Prisma.IntFieldUpdateOperationsInput | number
  cv?: Prisma.CvUpdateOneRequiredWithoutSectionsNestedInput
}

export type CvSectionUncheckedUpdateWithoutChunksInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  cvId?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCvSectionTypeFieldUpdateOperationsInput | $Enums.CvSectionType
  order?: Prisma.IntFieldUpdateOperationsInput | number
}

export type CvSectionCreateManyCvInput = {
  id?: string
  type: $Enums.CvSectionType
  order: number
}

export type CvSectionUpdateWithoutCvInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCvSectionTypeFieldUpdateOperationsInput | $Enums.CvSectionType
  order?: Prisma.IntFieldUpdateOperationsInput | number
  chunks?: Prisma.CvChunkUpdateManyWithoutSectionNestedInput
}

export type CvSectionUncheckedUpdateWithoutCvInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCvSectionTypeFieldUpdateOperationsInput | $Enums.CvSectionType
  order?: Prisma.IntFieldUpdateOperationsInput | number
  chunks?: Prisma.CvChunkUncheckedUpdateManyWithoutSectionNestedInput
}

export type CvSectionUncheckedUpdateManyWithoutCvInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  type?: Prisma.EnumCvSectionTypeFieldUpdateOperationsInput | $Enums.CvSectionType
  order?: Prisma.IntFieldUpdateOperationsInput | number
}

/**
 * Count Type CvSectionCountOutputType
 */

export type CvSectionCountOutputType = {
  chunks: number
}

export type CvSectionCountOutputTypeSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  chunks?: boolean | CvSectionCountOutputTypeCountChunksArgs
}

/**
 * CvSectionCountOutputType without action
 */
export type CvSectionCountOutputTypeDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSectionCountOutputType
   */
  select?: Prisma.CvSectionCountOutputTypeSelect<ExtArgs> | null
}

/**
 * CvSectionCountOutputType without action
 */
export type CvSectionCountOutputTypeCountChunksArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  where?: Prisma.CvChunkWhereInput
}

export type CvSectionSelect<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    cvId?: boolean
    type?: boolean
    order?: boolean
    cv?: boolean | Prisma.CvDefaultArgs<ExtArgs>
    chunks?: boolean | Prisma.CvSection$chunksArgs<ExtArgs>
    _count?: boolean | Prisma.CvSectionCountOutputTypeDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['cvSection']
>

export type CvSectionSelectCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    cvId?: boolean
    type?: boolean
    order?: boolean
    cv?: boolean | Prisma.CvDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['cvSection']
>

export type CvSectionSelectUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetSelect<
  {
    id?: boolean
    cvId?: boolean
    type?: boolean
    order?: boolean
    cv?: boolean | Prisma.CvDefaultArgs<ExtArgs>
  },
  ExtArgs['result']['cvSection']
>

export type CvSectionSelectScalar = {
  id?: boolean
  cvId?: boolean
  type?: boolean
  order?: boolean
}

export type CvSectionOmit<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = runtime.Types.Extensions.GetOmit<'id' | 'cvId' | 'type' | 'order', ExtArgs['result']['cvSection']>
export type CvSectionInclude<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  cv?: boolean | Prisma.CvDefaultArgs<ExtArgs>
  chunks?: boolean | Prisma.CvSection$chunksArgs<ExtArgs>
  _count?: boolean | Prisma.CvSectionCountOutputTypeDefaultArgs<ExtArgs>
}
export type CvSectionIncludeCreateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  cv?: boolean | Prisma.CvDefaultArgs<ExtArgs>
}
export type CvSectionIncludeUpdateManyAndReturn<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  cv?: boolean | Prisma.CvDefaultArgs<ExtArgs>
}

export type $CvSectionPayload<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  name: 'CvSection'
  objects: {
    cv: Prisma.$CvPayload<ExtArgs>
    chunks: Prisma.$CvChunkPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<
    {
      id: string
      cvId: string
      type: $Enums.CvSectionType
      order: number
    },
    ExtArgs['result']['cvSection']
  >
  composites: {}
}

export type CvSectionGetPayload<S extends boolean | null | undefined | CvSectionDefaultArgs> =
  runtime.Types.Result.GetResult<Prisma.$CvSectionPayload, S>

export type CvSectionCountArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = Omit<CvSectionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
  select?: CvSectionCountAggregateInputType | true
}

export interface CvSectionDelegate<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['CvSection']; meta: { name: 'CvSection' } }
  /**
   * Find zero or one CvSection that matches the filter.
   * @param {CvSectionFindUniqueArgs} args - Arguments to find a CvSection
   * @example
   * // Get one CvSection
   * const cvSection = await prisma.cvSection.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends CvSectionFindUniqueArgs>(
    args: Prisma.SelectSubset<T, CvSectionFindUniqueArgs<ExtArgs>>,
  ): Prisma.Prisma__CvSectionClient<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'findUnique', GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find one CvSection that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {CvSectionFindUniqueOrThrowArgs} args - Arguments to find a CvSection
   * @example
   * // Get one CvSection
   * const cvSection = await prisma.cvSection.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends CvSectionFindUniqueOrThrowArgs>(
    args: Prisma.SelectSubset<T, CvSectionFindUniqueOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__CvSectionClient<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first CvSection that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CvSectionFindFirstArgs} args - Arguments to find a CvSection
   * @example
   * // Get one CvSection
   * const cvSection = await prisma.cvSection.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends CvSectionFindFirstArgs>(
    args?: Prisma.SelectSubset<T, CvSectionFindFirstArgs<ExtArgs>>,
  ): Prisma.Prisma__CvSectionClient<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'findFirst', GlobalOmitOptions> | null,
    null,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find the first CvSection that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CvSectionFindFirstOrThrowArgs} args - Arguments to find a CvSection
   * @example
   * // Get one CvSection
   * const cvSection = await prisma.cvSection.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends CvSectionFindFirstOrThrowArgs>(
    args?: Prisma.SelectSubset<T, CvSectionFindFirstOrThrowArgs<ExtArgs>>,
  ): Prisma.Prisma__CvSectionClient<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'findFirstOrThrow', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Find zero or more CvSections that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CvSectionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all CvSections
   * const cvSections = await prisma.cvSection.findMany()
   *
   * // Get first 10 CvSections
   * const cvSections = await prisma.cvSection.findMany({ take: 10 })
   *
   * // Only select the `id`
   * const cvSectionWithIdOnly = await prisma.cvSection.findMany({ select: { id: true } })
   *
   */
  findMany<T extends CvSectionFindManyArgs>(
    args?: Prisma.SelectSubset<T, CvSectionFindManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions>
  >

  /**
   * Create a CvSection.
   * @param {CvSectionCreateArgs} args - Arguments to create a CvSection.
   * @example
   * // Create one CvSection
   * const CvSection = await prisma.cvSection.create({
   *   data: {
   *     // ... data to create a CvSection
   *   }
   * })
   *
   */
  create<T extends CvSectionCreateArgs>(
    args: Prisma.SelectSubset<T, CvSectionCreateArgs<ExtArgs>>,
  ): Prisma.Prisma__CvSectionClient<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'create', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Create many CvSections.
   * @param {CvSectionCreateManyArgs} args - Arguments to create many CvSections.
   * @example
   * // Create many CvSections
   * const cvSection = await prisma.cvSection.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   */
  createMany<T extends CvSectionCreateManyArgs>(
    args?: Prisma.SelectSubset<T, CvSectionCreateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many CvSections and returns the data saved in the database.
   * @param {CvSectionCreateManyAndReturnArgs} args - Arguments to create many CvSections.
   * @example
   * // Create many CvSections
   * const cvSection = await prisma.cvSection.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Create many CvSections and only return the `id`
   * const cvSectionWithIdOnly = await prisma.cvSection.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  createManyAndReturn<T extends CvSectionCreateManyAndReturnArgs>(
    args?: Prisma.SelectSubset<T, CvSectionCreateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'createManyAndReturn', GlobalOmitOptions>
  >

  /**
   * Delete a CvSection.
   * @param {CvSectionDeleteArgs} args - Arguments to delete one CvSection.
   * @example
   * // Delete one CvSection
   * const CvSection = await prisma.cvSection.delete({
   *   where: {
   *     // ... filter to delete one CvSection
   *   }
   * })
   *
   */
  delete<T extends CvSectionDeleteArgs>(
    args: Prisma.SelectSubset<T, CvSectionDeleteArgs<ExtArgs>>,
  ): Prisma.Prisma__CvSectionClient<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'delete', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Update one CvSection.
   * @param {CvSectionUpdateArgs} args - Arguments to update one CvSection.
   * @example
   * // Update one CvSection
   * const cvSection = await prisma.cvSection.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  update<T extends CvSectionUpdateArgs>(
    args: Prisma.SelectSubset<T, CvSectionUpdateArgs<ExtArgs>>,
  ): Prisma.Prisma__CvSectionClient<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'update', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Delete zero or more CvSections.
   * @param {CvSectionDeleteManyArgs} args - Arguments to filter CvSections to delete.
   * @example
   * // Delete a few CvSections
   * const { count } = await prisma.cvSection.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   *
   */
  deleteMany<T extends CvSectionDeleteManyArgs>(
    args?: Prisma.SelectSubset<T, CvSectionDeleteManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CvSections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CvSectionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many CvSections
   * const cvSection = await prisma.cvSection.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   *
   */
  updateMany<T extends CvSectionUpdateManyArgs>(
    args: Prisma.SelectSubset<T, CvSectionUpdateManyArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more CvSections and returns the data updated in the database.
   * @param {CvSectionUpdateManyAndReturnArgs} args - Arguments to update many CvSections.
   * @example
   * // Update many CvSections
   * const cvSection = await prisma.cvSection.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *
   * // Update zero or more CvSections and only return the `id`
   * const cvSectionWithIdOnly = await prisma.cvSection.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   *
   */
  updateManyAndReturn<T extends CvSectionUpdateManyAndReturnArgs>(
    args: Prisma.SelectSubset<T, CvSectionUpdateManyAndReturnArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'updateManyAndReturn', GlobalOmitOptions>
  >

  /**
   * Create or update one CvSection.
   * @param {CvSectionUpsertArgs} args - Arguments to update or create a CvSection.
   * @example
   * // Update or create a CvSection
   * const cvSection = await prisma.cvSection.upsert({
   *   create: {
   *     // ... data to create a CvSection
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the CvSection we want to update
   *   }
   * })
   */
  upsert<T extends CvSectionUpsertArgs>(
    args: Prisma.SelectSubset<T, CvSectionUpsertArgs<ExtArgs>>,
  ): Prisma.Prisma__CvSectionClient<
    runtime.Types.Result.GetResult<Prisma.$CvSectionPayload<ExtArgs>, T, 'upsert', GlobalOmitOptions>,
    never,
    ExtArgs,
    GlobalOmitOptions
  >

  /**
   * Count the number of CvSections.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CvSectionCountArgs} args - Arguments to filter CvSections to count.
   * @example
   * // Count the number of CvSections
   * const count = await prisma.cvSection.count({
   *   where: {
   *     // ... the filter for the CvSections we want to count
   *   }
   * })
   **/
  count<T extends CvSectionCountArgs>(
    args?: Prisma.Subset<T, CvSectionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], CvSectionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a CvSection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CvSectionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
   **/
  aggregate<T extends CvSectionAggregateArgs>(
    args: Prisma.Subset<T, CvSectionAggregateArgs>,
  ): Prisma.PrismaPromise<GetCvSectionAggregateType<T>>

  /**
   * Group by CvSection.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {CvSectionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   *
   **/
  groupBy<
    T extends CvSectionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<Prisma.Extends<'skip', Prisma.Keys<T>>, Prisma.Extends<'take', Prisma.Keys<T>>>,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: CvSectionGroupByArgs['orderBy'] }
      : { orderBy?: CvSectionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
      ? `Error: "by" must not be empty.`
      : HavingValid extends Prisma.False
        ? {
            [P in HavingFields]: P extends ByFields
              ? never
              : P extends string
                ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
                : [Error, 'Field ', P, ` in "having" needs to be provided in "by"`]
          }[HavingFields]
        : 'take' extends Prisma.Keys<T>
          ? 'orderBy' extends Prisma.Keys<T>
            ? ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields]
            : 'Error: If you provide "take", you also need to provide "orderBy"'
          : 'skip' extends Prisma.Keys<T>
            ? 'orderBy' extends Prisma.Keys<T>
              ? ByValid extends Prisma.True
                ? {}
                : {
                    [P in OrderFields]: P extends ByFields
                      ? never
                      : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                  }[OrderFields]
              : 'Error: If you provide "skip", you also need to provide "orderBy"'
            : ByValid extends Prisma.True
              ? {}
              : {
                  [P in OrderFields]: P extends ByFields
                    ? never
                    : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
                }[OrderFields],
  >(
    args: Prisma.SubsetIntersection<T, CvSectionGroupByArgs, OrderByArg> & InputErrors,
  ): {} extends InputErrors ? GetCvSectionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
  /**
   * Fields of the CvSection model
   */
  readonly fields: CvSectionFieldRefs
}

/**
 * The delegate class that acts as a "Promise-like" for CvSection.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__CvSectionClient<
  T,
  Null = never,
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: 'PrismaPromise'
  cv<T extends Prisma.CvDefaultArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.CvDefaultArgs<ExtArgs>>,
  ): Prisma.Prisma__CvClient<
    runtime.Types.Result.GetResult<Prisma.$CvPayload<ExtArgs>, T, 'findUniqueOrThrow', GlobalOmitOptions> | Null,
    Null,
    ExtArgs,
    GlobalOmitOptions
  >
  chunks<T extends Prisma.CvSection$chunksArgs<ExtArgs> = {}>(
    args?: Prisma.Subset<T, Prisma.CvSection$chunksArgs<ExtArgs>>,
  ): Prisma.PrismaPromise<
    runtime.Types.Result.GetResult<Prisma.$CvChunkPayload<ExtArgs>, T, 'findMany', GlobalOmitOptions> | Null
  >
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}

/**
 * Fields of the CvSection model
 */
export interface CvSectionFieldRefs {
  readonly id: Prisma.FieldRef<'CvSection', 'String'>
  readonly cvId: Prisma.FieldRef<'CvSection', 'String'>
  readonly type: Prisma.FieldRef<'CvSection', 'CvSectionType'>
  readonly order: Prisma.FieldRef<'CvSection', 'Int'>
}

// Custom InputTypes
/**
 * CvSection findUnique
 */
export type CvSectionFindUniqueArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
  /**
   * Filter, which CvSection to fetch.
   */
  where: Prisma.CvSectionWhereUniqueInput
}

/**
 * CvSection findUniqueOrThrow
 */
export type CvSectionFindUniqueOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
  /**
   * Filter, which CvSection to fetch.
   */
  where: Prisma.CvSectionWhereUniqueInput
}

/**
 * CvSection findFirst
 */
export type CvSectionFindFirstArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
  /**
   * Filter, which CvSection to fetch.
   */
  where?: Prisma.CvSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CvSections to fetch.
   */
  orderBy?: Prisma.CvSectionOrderByWithRelationInput | Prisma.CvSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CvSections.
   */
  cursor?: Prisma.CvSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CvSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CvSections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CvSections.
   */
  distinct?: Prisma.CvSectionScalarFieldEnum | Prisma.CvSectionScalarFieldEnum[]
}

/**
 * CvSection findFirstOrThrow
 */
export type CvSectionFindFirstOrThrowArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
  /**
   * Filter, which CvSection to fetch.
   */
  where?: Prisma.CvSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CvSections to fetch.
   */
  orderBy?: Prisma.CvSectionOrderByWithRelationInput | Prisma.CvSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for searching for CvSections.
   */
  cursor?: Prisma.CvSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CvSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CvSections.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   *
   * Filter by unique combinations of CvSections.
   */
  distinct?: Prisma.CvSectionScalarFieldEnum | Prisma.CvSectionScalarFieldEnum[]
}

/**
 * CvSection findMany
 */
export type CvSectionFindManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
  /**
   * Filter, which CvSections to fetch.
   */
  where?: Prisma.CvSectionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   *
   * Determine the order of CvSections to fetch.
   */
  orderBy?: Prisma.CvSectionOrderByWithRelationInput | Prisma.CvSectionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   *
   * Sets the position for listing CvSections.
   */
  cursor?: Prisma.CvSectionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Take `±n` CvSections from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   *
   * Skip the first `n` CvSections.
   */
  skip?: number
  distinct?: Prisma.CvSectionScalarFieldEnum | Prisma.CvSectionScalarFieldEnum[]
}

/**
 * CvSection create
 */
export type CvSectionCreateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
  /**
   * The data needed to create a CvSection.
   */
  data: Prisma.XOR<Prisma.CvSectionCreateInput, Prisma.CvSectionUncheckedCreateInput>
}

/**
 * CvSection createMany
 */
export type CvSectionCreateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to create many CvSections.
   */
  data: Prisma.CvSectionCreateManyInput | Prisma.CvSectionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * CvSection createManyAndReturn
 */
export type CvSectionCreateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * The data used to create many CvSections.
   */
  data: Prisma.CvSectionCreateManyInput | Prisma.CvSectionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * CvSection update
 */
export type CvSectionUpdateArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
  /**
   * The data needed to update a CvSection.
   */
  data: Prisma.XOR<Prisma.CvSectionUpdateInput, Prisma.CvSectionUncheckedUpdateInput>
  /**
   * Choose, which CvSection to update.
   */
  where: Prisma.CvSectionWhereUniqueInput
}

/**
 * CvSection updateMany
 */
export type CvSectionUpdateManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * The data used to update CvSections.
   */
  data: Prisma.XOR<Prisma.CvSectionUpdateManyMutationInput, Prisma.CvSectionUncheckedUpdateManyInput>
  /**
   * Filter which CvSections to update
   */
  where?: Prisma.CvSectionWhereInput
  /**
   * Limit how many CvSections to update.
   */
  limit?: number
}

/**
 * CvSection updateManyAndReturn
 */
export type CvSectionUpdateManyAndReturnArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * The data used to update CvSections.
   */
  data: Prisma.XOR<Prisma.CvSectionUpdateManyMutationInput, Prisma.CvSectionUncheckedUpdateManyInput>
  /**
   * Filter which CvSections to update
   */
  where?: Prisma.CvSectionWhereInput
  /**
   * Limit how many CvSections to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * CvSection upsert
 */
export type CvSectionUpsertArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
  /**
   * The filter to search for the CvSection to update in case it exists.
   */
  where: Prisma.CvSectionWhereUniqueInput
  /**
   * In case the CvSection found by the `where` argument doesn't exist, create a new CvSection with this data.
   */
  create: Prisma.XOR<Prisma.CvSectionCreateInput, Prisma.CvSectionUncheckedCreateInput>
  /**
   * In case the CvSection was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.CvSectionUpdateInput, Prisma.CvSectionUncheckedUpdateInput>
}

/**
 * CvSection delete
 */
export type CvSectionDeleteArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
  /**
   * Filter which CvSection to delete.
   */
  where: Prisma.CvSectionWhereUniqueInput
}

/**
 * CvSection deleteMany
 */
export type CvSectionDeleteManyArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Filter which CvSections to delete
   */
  where?: Prisma.CvSectionWhereInput
  /**
   * Limit how many CvSections to delete.
   */
  limit?: number
}

/**
 * CvSection.chunks
 */
export type CvSection$chunksArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvChunk
   */
  select?: Prisma.CvChunkSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvChunk
   */
  omit?: Prisma.CvChunkOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvChunkInclude<ExtArgs> | null
  where?: Prisma.CvChunkWhereInput
  orderBy?: Prisma.CvChunkOrderByWithRelationInput | Prisma.CvChunkOrderByWithRelationInput[]
  cursor?: Prisma.CvChunkWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.CvChunkScalarFieldEnum | Prisma.CvChunkScalarFieldEnum[]
}

/**
 * CvSection without action
 */
export type CvSectionDefaultArgs<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
> = {
  /**
   * Select specific fields to fetch from the CvSection
   */
  select?: Prisma.CvSectionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the CvSection
   */
  omit?: Prisma.CvSectionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.CvSectionInclude<ExtArgs> | null
}
